<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="css/styles.css">
<meta property="og:type" content="website">
<meta property="og:locale" content="en_GB">
<meta property="og:image" content="https://www.jamesl.dev/assets/img/og-image.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="jamesl.dev">
<meta property="og:image" content="https://www.jamesl.dev/assets/img/og-square.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="1200">
<meta property="og:image:alt" content="jamesl.dev">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@jamesldev">
<meta name="twitter:creator" content="@jamesldev">
<meta name="twitter:image" content="https://www.jamesl.dev/assets/img/og-image.png">
<meta name="twitter:image:alt" content="jamesl.dev">
